name: pyRevitDocsCI
on:
  # when PRs from forked repos are merged
  push:
    branches:
      - docs
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'pyrevitlib/**'
      - '*.md'
  # when PR from develop->master is created
  pull_request:
    branches:
      - master
    paths:
      - 'mkdocs.yml'
      - 'docs/**'
      - 'pyrevitlib/**'
      - '*.md'
  # manual run
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Prepare Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Prepare pipenv
        run: |
          pip install pipenv
          pipenv sync

      - run: pipenv run mkdocs gh-deploy --force
